### ISSUE TITLE
Automate fetching database dumps from S3

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/openstack-billing-from-db#13]
There's a regular cron job that dumps OpenStack databases into S3. Instead of requesting a dump be sent to use, we can feed the scripts into fetching the dumps directly from S3.

**Comment by joachimweyl** [comment]
@knikolla is this expected to be worked on this sprint or shall we push this out to the next sprint?

**Comment by knikolla** [comment]
I have been able to fetch the database dumps for S3, though for the moment only from a debug pod running in nerc-shift-0. Marking this as closed.
