### ISSUE TITLE
Update the OpenStack Invoice Script to include VMs that are shut off

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openstack-billing-from-db#18]
## Motivation
The decision was made to bill on VMs that are shut off as they retain the resources and block others from using them.

## Completion Criteria
Invoice Script returned VM time is no longer only for VMs that are on. VM time is calculated for all time a VM exists.

## Description
Update the Invoice Script to include time that VMs are shut off in the calculation of hours to bill on.

## Notes
- For now, the price will be the same for VMs if they are on or shut off because they are reserving the resources and not letting other users use them.

## Completion dates
Desired - 2023/11/22
Required - 2023/11/29

**Comment by knikolla** [comment]
@joachimweyl Will the price be the same for both on and off VMs?

**Comment by joachimweyl** [comment]
@knikolla for now, it will be the same price. If it is easy enough to code it might be worth having it be 2 separate variables in case.

**Comment by msdisme** [comment]
Notes from discussion with Wayne and Orran:
OpenStack Charging change 
   - Issue around it’s not just turning off VMs, will need to free up allocation to not be charged for A100.  May decide to be lenient on CPU, but not GPU.
   - Can we make changes to release it and not turn it on if GPU is not available?

**Comment by knikolla** [comment]
> Notes from discussion with Wayne and Orran:
> 
> OpenStack Charging change 
> 
>    - Issue around it’s not just turning off VMs, will need to free up allocation to not be charged for A100.  May decide to be lenient on CPU, but not GPU.
> 
>    - Can we make changes to release it and not turn it on if GPU is not available?
> 
> 

So you're saying to not count shut off time for cpu su, but only for gpu su?

**Comment by joachimweyl** [comment]
For now, we will count all shut-off time CPU and GPU. There may be a future time when we decide to "be Leinient" and not charge for shut-off time for CPUs.

**Comment by joachimweyl** [comment]
We will not merge the change until 2023/12/01. That being said once we have both approvals needed for the merge we can close this issue.

**Comment by knikolla** [comment]
@joachimweyl Instead of not merging this until Dec 1, I will extend the code in the PR to include a command line argument to toggle the behavior.

**Comment by joachimweyl** [comment]
that works, or just set the variable that tracks shut-off VMs to 0. whichever you prefer.
