### ISSUE TITLE
Gather and Process November OpenStack & Storage Invoice data

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openstack-billing-from-db#20]
- [x] Get DBs from @aabaris (or this is [automated](https://github.com/CCI-MOC/openstack-billing-from-db/issues/13))
- [x] process DBs (or this is [automated](https://github.com/CCI-MOC/openstack-billing-from-db/issues/14))
- [x] Provide CSVs to @naved001 to clean it up

**Comment by aabaris** [comment]
@knikolla you had mentioned that ColdFront DBs will no longer be needed in the future, will you still need ColdFront DB for this month or just nova databases?
