### ISSUE TITLE
Use EMAIL ADDRESS for the Manager (PI) field instead of USERNAME

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openstack-billing-from-db#41]
## Motivation
The username has some values that are not email addresses as originally assumed. We want email addresses as a way to capture their institution and an email makes it easier to reach them.

## Completion Criteria
Manager (PI) is filled with values from EMAIL ADDRESS field from ColdFront instead of USERNAME

## Description
- [ ] switch pull value to EMAIL ADDRESS
- [ ] test

## Completion dates
Desired - 2024-02-14
Required - TBD

**Comment by knikolla** [comment]
This will be closed once https://github.com/nerc-project/coldfront-plugin-api/pull/40 rolls into production on April 16
