### ISSUE TITLE
Create a way to differentiate between Lenovo A100 GPU usage and other A100 usage in OpenStack

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openstack-billing-from-db#43]
## Motivation
We need to prive invoice data to Lenovo for only their A100s so that we pay them for the time their GPUs are used. Closely related to this [issue](https://github.com/CCI-MOC/openshift-usage-scripts/issues/40).

## Completion Criteria
invoicing data has a way to track the difference between Lenovo and non-Lenovo GPUs. Or we generate a separate invoice for Lenovo that only shows their data.

## Description
- [x] @jtriley locate information on the back end that will allow us to differentiate between Lenovo and non-Lenovo GPUs, keep in mind we may have future loans so we will want to provide a numbering schema to the naming as well so we can differentiate between round 1, round 2, etc.
- [x] Brainstorm how to use this information and if it will be better to try to include it in some way with the invoice spreadsheet or if it will be better to generate a separate Lenovo invoice.
   - already leaning toward a separate invoice but am open to other ideas
- [x] Create an [issue](https://github.com/CCI-MOC/openstack-billing-from-db/issues/46) to update the OpenStack invoice script to include this data-gathering

## Completion dates
Desired - 2024-02-27
Required - 2024-04-05

**Comment by knikolla** [comment]
Easy to do using hypervisor name.

**Comment by joachimweyl** [comment]
If the 5 estimate was too much based on the ease of getting the hypervisor name please feel free to shrink the estimate.
