### ISSUE TITLE
Update OpenStack Invoice Script to create a Lenovo Loan only CSV

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openstack-billing-from-db#46]
## Motivation
We need to provide Lenovo with a usage list of how much their loaned nodes are being used

## Completion Criteria
A separate CSV is exported to provide Lenovo GPU usage only.

## Description
- [ ] current output becomes staging output
- [ ] Add new SU type OpenStack GPUA100SXM
- [ ] Create a new output that combines OpenStack GPUA100SXM4 with OpenStack GPUA100
- [ ] Then another CSV output which only includes the GPUA100SXM4 usage
- [ ] Test that MGHPCC CSV is the same
- [ ] Handoff to [new issue](https://github.com/CCI-MOC/openshift-usage-scripts/issues/46) to finish OpenShift and combination

## Completion dates
Desired - 2024-03-27
Required - 2024-04-18

**Comment by knikolla** [comment]
@joachimweyl I thought based on the discussions we had that we agreed to add a new row for SXM4s to the current CSVs and to split out the Lenovo CSV only as part of the `process_csv_report` step?

**Comment by joachimweyl** [comment]
Correct, I will update here.
